### ISSUE TITLE
GUI: Planung

### ISSUE THREAD

**Issue by Xeferis** [Saftladen-GmbH/CN-P108-Zeiterfassung#5]

**Comment by LumaKEKW** [comment]
Figma Design: https://www.figma.com/design/M32u2KnNzZ6ks6FYUMOqh4/Lucas-Mentel's-team-library?node-id=0-1&t=gviYHosnNYoAidma-0

**Comment by LumaKEKW** [comment]
![Side GUI](https://github.com/user-attachments/assets/c477073d-60ef-4894-b7ba-a4dc087dabb7)
![Main GUI](https://github.com/user-attachments/assets/0107eda5-d887-46c2-8077-8c71390bb0ed)
![Register GUI](https://github.com/user-attachments/assets/2d841e5c-4996-432c-8e7d-bb6bfb67c645)
Erste Prototypen der ersten drei Seiten. Weitere könnten folgen für bspw. Admin Funktionen.

**Comment by Xeferis** [comment]
Müssten wir mal gucken, welches CSS Framework, dann am nächsten an dein Design hier kommt. Auf den ersten Blick, würde ich fast sagen "Bootstrap". Die abgerundeten Buttons und Felder erinnern mich da sehr stark dran mit der NAV Bar. Vielleicht passt auch eins von den "minimals"

[CSS Frameworks](https://github.com/troxler/awesome-css-frameworks)

**Comment by Xeferis** [comment]
Das ist ein Test Kommentar

**Comment by Xeferis** [comment]
Das ist ein Testkommentar mit Erwähnung @LumaKEKW
